name: Chirpy CI/CD

on:
  # push:
  #   branches: [main]
  pull_request:
    branches: [main]

jobs:

  test:

    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: NPM install, build and test
        run: |
          npm install
          npm test
        env: 
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          SESSION_NAME: ${{ secrets.SESSION_NAME }}

  deploy:

      name: Deploy
      needs: [test]
      runs-on: ubuntu-latest

      steps:
        
        - name: Checkout
          uses: actions/checkout@v2
          with:
              fetch-depth: 0

          
        - name: Add remote origin to Heroku
          run: git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git

        - name: Deploy code to Heroku 
          run: git push heroku HEAD:main
