name: Chirpy CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  test:

    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: NPM install, build and test
        run: |
          npm install
          npm test
        env: 
          DATABASE_URL: ${{ env.DATABASE_URL }}
          SESSION_SECRET: ${{ env.SESSION_SECRET }}
          SESSION_NAME: ${{ env.SESSION_NAME }}